package com.wings.mile.model


class getdetails : ArrayList<getdriver>()
data class getdriver(
    var name: String?,
    var date_of_birth: String?,
    var usr_district: String?,
    var license_no: String?,
    var aadhar_no: String?,
    var email_id: String?,
    var gender: String?,
    var license_plate_no: String?,
    var phone_num: String?,
    var usr_state: String?,
    var vehicle_type_id: Int?,
    var vehicle_type_name: String?,
    var address: String?,
    var insurance_no: String?,
    var country: String?,
    var pincode: String?,
    var usr_img_file_location: String?,
    var usr_img_file_name: String?,
    var user_address: String?,
    var en_flag: String?,
    var aadhar_file_name: String?,
    var aadhar_file_location: String?,
    var drv_pan_no: String?,
    var panno_file_name: String?,
    var panno_file_location: String?,
    var licno_file_name: String?,
    var licno_file_location: String?,
    var insno_file_name: String?,
    var insno_file_location: String?,
    var plateno_file_name: String?,
    var plateno_file_location: String?,
    var doc_file_name: String?,
    var doc_file_location: String?,
    var user_id: Int,
    var first_Name: String?,
    var last_Name: String?,
    var district_id: Int,
    var new_userid: Int,
    var id_proof_name: String,
    var bank_Name: String,
    var branch_Name: String,
    var ifsc_Code: String,
    var bank_Img_File_Name: String,
    var bank_Img_File_Location: String,
    var account_Number: String,
    var bank_mobile_num: String,
    var driving_License_Expiry_Date: String,
    var vehicle_Insurance_Expiry_Date: String,
    var regstr_pymt_flg: String

    )
