package com.wings.mile.model


data class savedriver(
    var aadhar_no: String?,
    var country: String?,
    var date_of_birth: String?,
    var district: String?,
    var district_id: Int?,
    var doc_file_location: String?,
    var doc_file_name: String?,
    var doc_data: String?,
    var drv_aadhar_no: String?,
    var drv_insurance_no: String?,
    var drv_license_no: String?,
    var email_id: String?,
    var en_flag: String?,
    var first_name: String?,
    var gender: String?,
    var image_data: String?,
    var last_name: String?,
    var license_plate_no: String?,
    var phone_number: String?,
    var pincode: String?,
    var state: String?,
    var user_address: String?,
    var user_id: Int?,
    var user_password: String?,
    var user_type_flg: String?,
    var usr_img_file_location: String?,
    var usr_img_file_name: String?,
    var aadhar_file_name: String?,
    var aadhar_data: String?,
    var aadhar_file_location: String?,
    var drv_pan_no: String?,
    var panno_file_name: String?,
    var panno_file_location: String?,
    var pan_data: String?,
    var licno_file_name: String?,
    var license_data: String?,
    var licno_file_location: String?,
    var insno_file_name: String?,
    var insurance_data: String?,
    var insno_file_location: String?,
    var plateno_file_name: String?,
    var plateNo_data: String?,
    var plateno_file_location: String?,
    var vehicle_type_id: Int?,
    var vehicle_name: String?,
    var new_userid: Int?,
    var id_Proof_Name: String?,
    var  comments :String?,
    var driving_License_Expiry_Date: String?,
    var vehicle_Insurance_Expiry_Date: String?


)
